export type FeatureQualityFlag =
  | 'invalid-geometry'
  | 'srid-mismatch'
  | 'missing-code'
  | 'duplicate-guid'
  | 'endpoint-duplicate'
  | 'duplicate-candidate'
  | 'reverse-duplicate-candidate'
  | 'short-segment'
  | 'duplicate-geometry'
  | 'reverse-duplicate-geometry'
  | 'spec-defaulted'
  | 'height-defaulted'
  | 'endpoint-unmatched'
  | 'merge-candidate'
